import 'package:yg_app/model/response/fiber_response/fiber_specification.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DataYarn {
/*
{
  "spc_id": 46,
  "material": "Cotton",
  "blend": null,
  "locality": null,
  "pattern": "Regular/Plain",
  "pattern_charectristic": "Regular",
  "orientation": "Weft",
  "twist_direction": null,
  "count": null,
  "product_year": "1970",
  "is_offering": "1",
  "sort_order": 1
}
*/

  int? spcId;
  String? material;
  String? blend;
  String? locality;
  String? pattern;
  String? patternCharectristic;
  String? orientation;
  String? twistDirection;
  String? count;
  String? productYear;
  String? isOffering;
  int? sortOrder;

  DataYarn({
    this.spcId,
    this.material,
    this.blend,
    this.locality,
    this.pattern,
    this.patternCharectristic,
    this.orientation,
    this.twistDirection,
    this.count,
    this.productYear,
    this.isOffering,
    this.sortOrder,
  });
  DataYarn.fromJson(Map<String, dynamic> json) {
    spcId = json['spc_id']?.toInt();
    material = json['material']?.toString();
    blend = json['blend']?.toString();
    locality = json['locality']?.toString();
    pattern = json['pattern']?.toString();
    patternCharectristic = json['pattern_charectristic']?.toString();
    orientation = json['orientation']?.toString();
    twistDirection = json['twist_direction']?.toString();
    count = json['count']?.toString();
    productYear = json['product_year']?.toString();
    isOffering = json['is_offering']?.toString();
    sortOrder = json['sort_order']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['spc_id'] = spcId;
    data['material'] = material;
    data['blend'] = blend;
    data['locality'] = locality;
    data['pattern'] = pattern;
    data['pattern_charectristic'] = patternCharectristic;
    data['orientation'] = orientation;
    data['twist_direction'] = twistDirection;
    data['count'] = count;
    data['product_year'] = productYear;
    data['is_offering'] = isOffering;
    data['sort_order'] = sortOrder;
    return data;
  }
}

// class DataFiber {
// /*
// {
//   "spc_id": 84,
//   "category_id": "1",
//   "business_area": "Fiber",
//   "locality": "LOCAL",
//   "material": "Cotton",
//   "length": "11",
//   "grade": "Virgin",
//   "apperance": null,
//   "brand": "Brand 2",
//   "product_year": "2022",
//   "is_offering": "1",
//   "sort_order": 1
// }
// */
//
//   int? spcId;
//   String? categoryId;
//   String? businessArea;
//   String? locality;
//   String? material;
//   String? length;
//   String? grade;
//   String? apperance;
//   String? brand;
//   String? productYear;
//   String? isOffering;
//   int? sortOrder;
//
//   DataFiber({
//     this.spcId,
//     this.categoryId,
//     this.businessArea,
//     this.locality,
//     this.material,
//     this.length,
//     this.grade,
//     this.apperance,
//     this.brand,
//     this.productYear,
//     this.isOffering,
//     this.sortOrder,
//   });
//   DataFiber.fromJson(Map<String, dynamic> json) {
//     spcId = json['spc_id']?.toInt();
//     categoryId = json['category_id']?.toString();
//     businessArea = json['business_area']?.toString();
//     locality = json['locality']?.toString();
//     material = json['material']?.toString();
//     length = json['length']?.toString();
//     grade = json['grade']?.toString();
//     apperance = json['apperance']?.toString();
//     brand = json['brand']?.toString();
//     productYear = json['product_year']?.toString();
//     isOffering = json['is_offering']?.toString();
//     sortOrder = json['sort_order']?.toInt();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['spc_id'] = spcId;
//     data['category_id'] = categoryId;
//     data['business_area'] = businessArea;
//     data['locality'] = locality;
//     data['material'] = material;
//     data['length'] = length;
//     data['grade'] = grade;
//     data['apperance'] = apperance;
//     data['brand'] = brand;
//     data['product_year'] = productYear;
//     data['is_offering'] = isOffering;
//     data['sort_order'] = sortOrder;
//     return data;
//   }
// }

class MyProductsData {
/*
{
  "fiber": [
    {
      "spc_id": 84,
      "category_id": "1",
      "business_area": "Fiber",
      "locality": "LOCAL",
      "material": "Cotton",
      "length": "11",
      "grade": "Virgin",
      "apperance": null,
      "brand": "Brand 2",
      "product_year": "2022",
      "is_offering": "1",
      "sort_order": 1
    }
  ],
  "yarn": [
    {
      "spc_id": 46,
      "material": "Cotton",
      "blend": null,
      "locality": null,
      "pattern": "Regular/Plain",
      "pattern_charectristic": "Regular",
      "orientation": "Weft",
      "twist_direction": null,
      "count": null,
      "product_year": "1970",
      "is_offering": "1",
      "sort_order": 1
    }
  ]
}
*/

  List<Specification?>? fiber;
  List<DataYarn?>? yarn;

  MyProductsData({
    this.fiber,
    this.yarn,
  });
  MyProductsData.fromJson(Map<String, dynamic> json) {
    if (json['fiber'] != null) {
      final v = json['fiber'];
      final arr0 = <Specification>[];
      v.forEach((v) {
        arr0.add(Specification.fromJson(v));
      });
      fiber = arr0;
    }
    if (json['yarn'] != null) {
      final v = json['yarn'];
      final arr0 = <DataYarn>[];
      v.forEach((v) {
        arr0.add(DataYarn.fromJson(v));
      });
      yarn = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (fiber != null) {
      final v = fiber;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['fiber'] = arr0;
    }
    if (yarn != null) {
      final v = yarn;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['yarn'] = arr0;
    }
    return data;
  }
}

class MyProductsResponse {
/*
{
  "status": true,
  "response_code": 200,
  "data": {
    "fiber": [
      {
        "spc_id": 84,
        "category_id": "1",
        "business_area": "Fiber",
        "locality": "LOCAL",
        "material": "Cotton",
        "length": "11",
        "grade": "Virgin",
        "apperance": null,
        "brand": "Brand 2",
        "product_year": "2022",
        "is_offering": "1",
        "sort_order": 1
      }
    ],
    "yarn": [
      {
        "spc_id": 46,
        "material": "Cotton",
        "blend": null,
        "locality": null,
        "pattern": "Regular/Plain",
        "pattern_charectristic": "Regular",
        "orientation": "Weft",
        "twist_direction": null,
        "count": null,
        "product_year": "1970",
        "is_offering": "1",
        "sort_order": 1
      }
    ]
  },
  "message": "Data fetched successfully!!!"
}
*/

  bool? status;
  int? responseCode;
  MyProductsData? data;
  String? message;

  MyProductsResponse({
    this.status,
    this.responseCode,
    this.data,
    this.message,
  });
  MyProductsResponse.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    responseCode = json['response_code']?.toInt();
    data = (json['data'] != null) ? MyProductsData.fromJson(json['data']) : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['response_code'] = responseCode;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
