import 'package:yg_app/model/response/fiber_response/fiber_specification.dart';
import 'package:yg_app/model/response/stocklot_repose/stocklot_specification_response.dart';
import 'package:yg_app/model/response/yarn_response/yarn_specification_response.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// class MatchedResponseDataFiberPictures {
// /*
// {
//   "picture": "http://yarnonline.net/dev/public/storage/fiber_pictures/29/e8e1fb90df4ecefe526689b6a97acf1377b06e70-a26f-4429-bdd1-f39828ecf96c8048431604809265520.jpg"
// }
// */
//
//   String? picture;
//
//   MatchedResponseDataFiberPictures({
//     this.picture,
//   });
//   MatchedResponseDataFiberPictures.fromJson(Map<String, dynamic> json) {
//     picture = json['picture']?.toString();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['picture'] = picture;
//     return data;
//   }
// }
//
// class MatchedResponseDataFiber {
// /*
// {
//   "spc_id": 2,
//   "category_id": "1",
//   "business_area": "Fiber",
//   "locality": "LOCAL",
//   "material": "Cotton",
//   "length": null,
//   "grade": "Virgin",
//   "micronaire": null,
//   "moisture": null,
//   "trash": "20",
//   "rd": "11",
//   "gpt": "49",
//   "apperance": null,
//   "brand": "Brand 1",
//   "product_year": "2022",
//   "origin": null,
//   "city_state": null,
//   "port": null,
//   "lot_number": "3265",
//   "price_unit": " 36",
//   "unit_count": null,
//   "delivery_period": "Ready Stock",
//   "available": null,
//   "price_terms": "LC",
//   "min_quantity": "56",
//   "description": "test",
//   "is_offering": "1",
//   "is_featured": "0",
//   "is_verified": "0",
//   "pictures": [
//     {
//       "picture": "http://yarnonline.net/dev/public/storage/fiber_pictures/29/e8e1fb90df4ecefe526689b6a97acf1377b06e70-a26f-4429-bdd1-f39828ecf96c8048431604809265520.jpg"
//     }
//   ],
//   "certifications": [
//     null
//   ],
//   "sort_order": 1
// }
// */
//
//   int? spcId;
//   String? categoryId;
//   String? businessArea;
//   String? locality;
//   String? material;
//   String? length;
//   String? grade;
//   String? micronaire;
//   String? moisture;
//   String? trash;
//   String? rd;
//   String? gpt;
//   String? apperance;
//   String? brand;
//   String? productYear;
//   String? origin;
//   String? cityState;
//   String? port;
//   String? lotNumber;
//   String? priceUnit;
//   String? unitCount;
//   String? deliveryPeriod;
//   String? available;
//   String? priceTerms;
//   String? minQuantity;
//   String? description;
//   String? isOffering;
//   String? isFeatured;
//   String? isVerified;
//   List<MatchedResponseDataFiberPictures?>? pictures;
//   List<MatchedResponseDataFiberCertifications?>? certifications;
//   int? sortOrder;
//
//   MatchedResponseDataFiber({
//     this.spcId,
//     this.categoryId,
//     this.businessArea,
//     this.locality,
//     this.material,
//     this.length,
//     this.grade,
//     this.micronaire,
//     this.moisture,
//     this.trash,
//     this.rd,
//     this.gpt,
//     this.apperance,
//     this.brand,
//     this.productYear,
//     this.origin,
//     this.cityState,
//     this.port,
//     this.lotNumber,
//     this.priceUnit,
//     this.unitCount,
//     this.deliveryPeriod,
//     this.available,
//     this.priceTerms,
//     this.minQuantity,
//     this.description,
//     this.isOffering,
//     this.isFeatured,
//     this.isVerified,
//     this.pictures,
//     this.certifications,
//     this.sortOrder,
//   });
//   MatchedResponseDataFiber.fromJson(Map<String, dynamic> json) {
//     spcId = json['spc_id']?.toInt();
//     categoryId = json['category_id']?.toString();
//     businessArea = json['business_area']?.toString();
//     locality = json['locality']?.toString();
//     material = json['material']?.toString();
//     length = json['length']?.toString();
//     grade = json['grade']?.toString();
//     micronaire = json['micronaire']?.toString();
//     moisture = json['moisture']?.toString();
//     trash = json['trash']?.toString();
//     rd = json['rd']?.toString();
//     gpt = json['gpt']?.toString();
//     apperance = json['apperance']?.toString();
//     brand = json['brand']?.toString();
//     productYear = json['product_year']?.toString();
//     origin = json['origin']?.toString();
//     cityState = json['city_state']?.toString();
//     port = json['port']?.toString();
//     lotNumber = json['lot_number']?.toString();
//     priceUnit = json['price_unit']?.toString();
//     unitCount = json['unit_count']?.toString();
//     deliveryPeriod = json['delivery_period']?.toString();
//     available = json['available']?.toString();
//     priceTerms = json['price_terms']?.toString();
//     minQuantity = json['min_quantity']?.toString();
//     description = json['description']?.toString();
//     isOffering = json['is_offering']?.toString();
//     isFeatured = json['is_featured']?.toString();
//     isVerified = json['is_verified']?.toString();
//     if (json['pictures'] != null) {
//       final v = json['pictures'];
//       final arr0 = <MatchedResponseDataFiberPictures>[];
//       v.forEach((v) {
//         arr0.add(MatchedResponseDataFiberPictures.fromJson(v));
//       });
//       pictures = arr0;
//     }
//     >>>>>>error<<<<<<
//     sortOrder = json['sort_order']?.toInt();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['spc_id'] = spcId;
//     data['category_id'] = categoryId;
//     data['business_area'] = businessArea;
//     data['locality'] = locality;
//     data['material'] = material;
//     data['length'] = length;
//     data['grade'] = grade;
//     data['micronaire'] = micronaire;
//     data['moisture'] = moisture;
//     data['trash'] = trash;
//     data['rd'] = rd;
//     data['gpt'] = gpt;
//     data['apperance'] = apperance;
//     data['brand'] = brand;
//     data['product_year'] = productYear;
//     data['origin'] = origin;
//     data['city_state'] = cityState;
//     data['port'] = port;
//     data['lot_number'] = lotNumber;
//     data['price_unit'] = priceUnit;
//     data['unit_count'] = unitCount;
//     data['delivery_period'] = deliveryPeriod;
//     data['available'] = available;
//     data['price_terms'] = priceTerms;
//     data['min_quantity'] = minQuantity;
//     data['description'] = description;
//     data['is_offering'] = isOffering;
//     data['is_featured'] = isFeatured;
//     data['is_verified'] = isVerified;
//     if (pictures != null) {
//       final v = pictures;
//       final arr0 = [];
//       v!.forEach((v) {
//         arr0.add(v!.toJson());
//       });
//       data['pictures'] = arr0;
//     }
//     >>>>>>error<<<<<<
//     data['sort_order'] = sortOrder;
//     return data;
//   }
// }

class MatchedResponseData {
/*
{
  "fiber": [
    {
      "spc_id": 2,
      "category_id": "1",
      "business_area": "Fiber",
      "locality": "LOCAL",
      "material": "Cotton",
      "length": null,
      "grade": "Virgin",
      "micronaire": null,
      "moisture": null,
      "trash": "20",
      "rd": "11",
      "gpt": "49",
      "apperance": null,
      "brand": "Brand 1",
      "product_year": "2022",
      "origin": null,
      "city_state": null,
      "port": null,
      "lot_number": "3265",
      "price_unit": " 36",
      "unit_count": null,
      "delivery_period": "Ready Stock",
      "available": null,
      "price_terms": "LC",
      "min_quantity": "56",
      "description": "test",
      "is_offering": "1",
      "is_featured": "0",
      "is_verified": "0",
      "pictures": [
        {
          "picture": "http://yarnonline.net/dev/public/storage/fiber_pictures/29/e8e1fb90df4ecefe526689b6a97acf1377b06e70-a26f-4429-bdd1-f39828ecf96c8048431604809265520.jpg"
        }
      ],
      "certifications": [
        null
      ],
      "sort_order": 1
    }
  ]
}
*/

  List<Specification>? fiber;
  List<YarnSpecification>? yarnSpecification;
  List<StockLotSpecification>? stockLotSpecification;

  MatchedResponseData({this.fiber, this.yarnSpecification,this.stockLotSpecification});

  MatchedResponseData.fromJson(Map<String, dynamic> json) {
    if (json['fiber'] != null) {
      final v = json['fiber'];
      final arr0 = <Specification>[];
      v.forEach((v) {
        arr0.add(Specification.fromJson(v));
      });
      fiber = arr0;
    }

    if (json['yarn'] != null) {
      final v = json['yarn'];
      final arr0 = <YarnSpecification>[];
      v.forEach((v) {
        arr0.add(YarnSpecification.fromJson(v));
      });
      yarnSpecification = arr0;
    }

    if (json['stocklot'] != null) {
      final v = json['stocklot'];
      final arr0 = <StockLotSpecification>[];
      v.forEach((v) {
        arr0.add(StockLotSpecification.fromJson(v));
      });
      stockLotSpecification = arr0;
    }
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (fiber != null) {
      final v = fiber;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v.toJson());
      });
      data['fiber'] = arr0;
    }
    if (yarnSpecification != null) {
      final v = yarnSpecification;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v.toJson());
      });
      data['yarn'] = arr0;
    }

    if (stockLotSpecification != null) {
      final v = stockLotSpecification;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v.toJson());
      });
      data['stocklot'] = arr0;
    }
    return data;
  }
}

class MatchedResponse {
/*
{
  "status": true,
  "response_code": 200,
  "data": {
    "fiber": [
      {
        "spc_id": 2,
        "category_id": "1",
        "business_area": "Fiber",
        "locality": "LOCAL",
        "material": "Cotton",
        "length": null,
        "grade": "Virgin",
        "micronaire": null,
        "moisture": null,
        "trash": "20",
        "rd": "11",
        "gpt": "49",
        "apperance": null,
        "brand": "Brand 1",
        "product_year": "2022",
        "origin": null,
        "city_state": null,
        "port": null,
        "lot_number": "3265",
        "price_unit": " 36",
        "unit_count": null,
        "delivery_period": "Ready Stock",
        "available": null,
        "price_terms": "LC",
        "min_quantity": "56",
        "description": "test",
        "is_offering": "1",
        "is_featured": "0",
        "is_verified": "0",
        "pictures": [
          {
            "picture": "http://yarnonline.net/dev/public/storage/fiber_pictures/29/e8e1fb90df4ecefe526689b6a97acf1377b06e70-a26f-4429-bdd1-f39828ecf96c8048431604809265520.jpg"
          }
        ],
        "certifications": [
          null
        ],
        "sort_order": 1
      }
    ]
  },
  "message": "Data fetched successfully!!!"
}
*/

  bool? status;
  int? responseCode;
  MatchedResponseData? data;
  String? message;

  MatchedResponse({
    this.status,
    this.responseCode,
    this.data,
    this.message,
  });

  MatchedResponse.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    responseCode = json['response_code']?.toInt();
    if (json['data'] is List<dynamic>) {
      data = null;
    } else {
      data = (json['data'] != null)
          ? MatchedResponseData.fromJson(json['data'])
          : null;
    }
    message = json['message']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['response_code'] = responseCode;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
